#!/usr/bin/env bash

export PRESERVE_XII_ENV=${PRESERVE_XII_ENV:-0}

if [ -f $(pwd)/.xii-env ]; then
  echo "Loading xii-env..."
  source $(pwd)/.xii-env
fi

if [ -z ${XII_image} ] ||
   [ -z ${XII_user} ] ||
   [ -z ${XII_password} ]; then
  echo "!! no working setup found. Create .xii-env in !!"
  echo "!! top level source directory.                !!"
  exit 1
fi

if [ "x${PRESERVE_XII_ENV}" == "x0" ]; then
  rm -rf ~/.xii
fi


ACTION=$1
shift

if [ "x${ACTION}" == "xgate" ]; then
    tox -e gate
elif [ "x${ACTION}" == "xlocal" ]; then
    pytest tests/integration $@
else
    tox -e integration
fi

exit $?
