#!/usr/bin/env bash

function info() { echo -e "\033[0;34m[INFO ]   $@\033[0m"; }
function section() { echo -e "\n\033[1;34m[INFO ] $@...\033[0m"; }
function warn() { echo -e "\033[1;31m[WARN ] $@\033[0m"; }
function fatal() { echo -e "\033[0;31m[FATAL] $@\033[0m"; exit 1; }

if ! which tox &>/dev/null; then
  warn "Could not find tox. tox is required to run the tests"
  fatal "Install tox package (mostly python-tox) or pip install tox"
fi

if [ "x$1" == "xtox" ]; then
  if [ "x$2" == "xcov" ]; then
    echo "tox with coveralls"
    tox -e unitwithcov
  else
    echo "tox without coveralls"
    tox -e unit
  fi
  exit $?
else
  if ! which ptw &>/dev/null; then
    pip install pytest-watch
  fi
  ptw tests/unit
fi

