#!/usr/bin/env bash

function info() { echo -e "\033[0;34m[INFO ]   $@\033[0m"; }
function section() { echo -e "\n\033[1;34m[INFO ] $@...\033[0m"; }
function warn() { echo -e "\033[1;31m[WARN ] $@\033[0m"; }
function fatal() { echo -e "\033[0;31m[FATAL] $@\033[0m"; exit 1; }

if ! which tox &>/dev/null; then
  warn "Could not find tox. tox is required to run the tests"
  fatal "Install tox package (mostly python-tox) or pip install tox"
fi

SOURCE_ROOT=$(pwd)/..

pushd ${SOURCE_ROOT} > /dev/null

tox -e unit
STATUS=$?

popd > /dev/null
exit ${STATUS}

